POETRY     = poetry run
SOURCEDIR  = docs/source
BUILDDIR   = docs/build
PACKAGEDIR = client

.PHONY: docs docs-clean docs-live

# Build documentation
docs:
	$(POETRY) sphinx-build -a "$(SOURCEDIR)" "$(BUILDDIR)/html"

# Remove documentation outputs
# This includes the api dir as it's autogenerated with sphinx-build
docs-clean:
	rm -r "$(BUILDDIR)" "$(SOURCEDIR)/api"

# Spin up a local server to serve documentation pages
# Auto-reloads when code changes in PACKAGEDIR are made
docs-live:
	$(POETRY) sphinx-autobuild --open-browser --watch "$(PACKAGEDIR)" -a "$(SOURCEDIR)" "$(BUILDDIR)/html"
