# REF: https://github.com/UQComputingSociety/uqcsbot-discord/blob/main/.github/workflows/setup-python/action.yml

name: Run code checks

on:
  push:
    branches: [ main ]
  pull_request: []

env: 
  PYTHON_VERSION: '3.10'
  POETRY_VERSION: '1.8.3'

jobs:
  styling:
    name: Run code styling
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # Local action that tries to cache as much of python & poetry as possible
      - name: Setup environment
        uses: ./.github/workflows/setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Check with black
        run: poetry run black .

